name: Java CI on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Basic plugin version verification
        run: java -ea scripts/CheckPomVersions.java

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean test spotless:check ossindex:audit
